import { randomInt } from "./util.js";

export const TIPS = [
    "Why can't I sleep?",
    "My telegram username is onion27 and here's the tip.",
    "There are random music names in the tips. Hope you will see them, ha!",
    "Wanna get some friends... but hold on.",
    "I'll never forget to add a comma after writing a tip... I just ran into problem because of that.",
    "The life is in a mess.",
    "Type her name.",
    "Let's use Firefox, shall we?",
    "Can I live in a story, instead of a boring and cruel world?",
    'Akiyama Mizuki is a character from "Hatsune Miku: Colorful Stage". ',
    "There is also a tip that is empty by the way.",
    "Don't you know what I don't know?",
    "Deno is a great runtime. And a great LSP.",
    "maimai DX is not a washing machine!",
    "I want to commit suicide time to time. The reason why I'm still alive is because they (ways to commit suicide) all looks painful (and they actually are).",
    "Forsaken Tale",
    "There are lots of garbage repository in my Github account. They were created by me when I was really, really young. Like I was literally a child that time.",
    "Will anyone really read and explore my homepage? I don't know. I just randomly put anything I want to put here.",
    "FONT TEST AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz0123456789~!@#$%^&*()`<>,./[]{}|\\'\"-_+=",
    "I use neovim for almost everything.",
    "There are some hidden content on the page.",
    "undefined (this is fake, as well.)",
    "Don't forget to update your system.",
    '"25-ji, Nightcord de" means meeting on Nightcord in 25:00.',
    "I'm so tired...",
    "Welcome to yet another recreational programming session, with 27Onion!",
    "Writing Haskell is like training my brain.",
    "Tips are just me mumbling alone in the late night. Don't care about it!",
    "CHUNITHM is also a fun game to play.",
    "LGBTQ+ rights matters.",
    "I'm using paru as the AUR helper.",
    "Recollect Lines",
    "I block whoever makes me mad.",
    "Never touch the truth.",
    "null",
    ":3",
    "Why are you looking at a loser's webpage?",
    "I'm really tired writing these tips...",
    "acta est fabula, plaudite",
    "It's not bad toe write C code sometimes.",
    "Fuckoff X11!",
    "I'm hungry...",
    "I wish I could be Mizuki or Saturday...",
    "Wanna have a Margherita Pizza? I love eating 'em.",
    "Good night.",
    "",
    'Why do we say "good night"? Because we want to wish each other happiness in our dreams. Because we want to share the following day with each other. Because we want our rests to matter just as much to us as our battles. We say "good night" to bookend chapters of our lives, every single day. Every single night. But every "good night" is only a promise of a new day tomorrow. Even with each "goodbye", we wish to each other to see ourselves again. So when we say "good night", it\'s not the end. It\'s the promise at every dusk to soon see tomorrow\'s dawn. See you tomorrow. Good night.',
    "91",
    "maimai DX is fun to play.",
    "QZKago Requiem",
    "This is my homepage.",
    "Oh la la.",
    "Smoking...",
    "Open source is good. Close source is bad.",
    "Cheeses are good. I love eating 'em.",
    "676767676767676767676767676767676767676767676767676767676767676767676767",
    "One of my best friends died in Mar 5, 2021 due to committing suicide.",
    "Racism, transphobic, homophobic and people like that will get an instant block from me.",
    "Even though I want to die everyday, I still sincerely wish everybody else to live healthily and happily. So, cheer up if you're reading this!",
    "There's a man in between, in between.",
    "My birthday? ...it's on Feb 1st.",
    "Barium chloride is bitter. Like, very very bitter. Never try eating this!",
    "祈 -我ら神祖と共に歩む者なり-",
    "CLAUDIA -libertia-",
    "I'll take a break after writing this tip.",
    "Mumble mumble...",
    'If you see null in tips, it\'s not a mistake. There actually exists a tip that says, well, "null"!',
    "Do you know my telegram? You might find it in a tip.",
    "The world is dumbass.",
    "I hate the real world, very, very much.",
    "I can't see hope in my life.",
    "tmux is great, try learning how to use it.",
    "Rust is a great programming language. Not perfect, but great enough.",
    "PANDORA PARADOXXX",
    "DELTARUNE is really fun to play.",
    "Do you know how I shuffle the tips? I just Vi[!shuf<CR> and it's done. And also I need to put a ] here to prevent messing up indents in my editor.",
    "Most of GUI ignores keyboard centric user experience. Hence they sucks.",
    "I fail on everything. I'm just a loser, I have to admit.",
    "I don't like drinking coke.",
    "I love watching Tsoding streams.",
    "... wouldn't it be better for me to disappear from the world?",
    "Ah...",
    "Could you find Tsuki Tasogare?",
    "There are many easter eggs in the page, just trigger them by typing random words on keyboard.",
    "You can scroll on the webpage. You might already knew that.",
    "Rolling on the ground, jumping over woods...",
    "A brown fox jumps over the lazy dog.",
    "Modal keybinds are good!",
    "Vibe coding is a lie.",
    "Yoisaki Kanade, Asahina Mafuyu, Shinonome Ena and Akiyama Mizuki are members of 25-ji, Nightcord de.",
    "Rhythm Doctor is a good game to play.",
    "I'm horribly near-sighted. I might become blind someday. That's scary...",
    "Ooh...",
    "vivid/stasis is a fun rhythm game, and it's free on Steam!",
    "Beware the man who speaks in hands.",
    "Pink is my favorite color.",
    "So tired.",
    "Here is a secret way to reload the page. Do you know that?",
    "AI sucks.",
    "STARGAZERS",
    "You can create an issue on the repository if there's anything wrong with the website!",
    "I like seeing Saturday Tasogare and Allison Allister together. They're just so sweet oh my god",
    "I want to start an ARG or something... but I don't really have a plan.",
    "Rendering texts correctly is way harder than you might think.",
    "To be or not to be, that is the question.",
    "Do you know the famous KONAMI cheat code?",
    "Why am I writing these tips?",
    "*brushing hair*",
    "Hyprland",
    "27 was my student number in the primary school, and Onion is my nickname given by a friend.",
    "Transgender rights matters.",
    "Please respect to everyone's gender identity, and use the correct pronoun they claim. Use the gender neutral expression if you are not sure.",
    "Apple juice is good to drink.",
    "STARCRASHERS",
    "Never forget to add semicolon after CSS statement...",
    "Egg: Not too important, not too unimportant.",
    "I'm kinda wanna sleep at this point.",
    "I can't think...",
    "Have I done this for 8266 times?",
    "Hamasushi is delicious.",
    "I'm already using Deno everywhere. Who cares about NodeJS?",
    "Why Japanese doesn't allow us to play ONGEKI?",
    "Ah, Saturday Tasogare. How cute she is!",
    "Will there be another world after dying? I don't know. I tried, but I failed.",
    "I wish I could see Saturday on the page...",
    "I hate writing shell scripts. So I just go straight writing a new project in Rust.",
    "I fuckin' hate Windows.",
    "Do you know what I know?",
    "What about playing UNDERTALE?",
    "ONGEKI is really really fun.",
    "Akiyama Yuuki is Akiyama Mizuki's sister.",
    "The tips will be shuffled after writing, but some of them are written in order.",
    "Where's Tsuki Tasogare?",
    "Saturday Tasogare and Allison Tasogare(Allister) got married in the game polymorphite oh my god aaahhhhh i fuckin' love it",
    "The font used on this website is called Liberation Serif.",
    "I'm running out of money...",
];

let current_tip = null;

/**
 * @returns {String}
 */
export function get_tip() {
    if (current_tip === null) {
        current_tip = TIPS[randomInt(0, TIPS.length)];
    }
    return current_tip;
}
