import { randomInt } from "./util.js";

export const TIPS = [
    "Ah...",
    "My MBTI is available somewhere...",
    "There are random music names in the tips. Hope you will see them, ha!",
    "It's not bad toe write C code sometimes.",
    "Yoisaki Kanade, Asahina Mafuyu, Shinonome Ena and Akiyama Mizuki are members of 25-ji, Nightcord de.",
    "Transgender rights matters.",
    "CLAUDIA -libertia-",
    "I'm already using Deno everywhere. Who cares about NodeJS?",
    "Never touch the truth.",
    "My birthday? ...it's on Feb 1st.",
    "If someone are talking about benefits of traditional medicine, I'll ban them in no time.",
    "Chinese traditional culture, sucks.",
    "What about playing UNDERTALE?",
    "You can scroll on the webpage. You might already knew that.",
    "You can create an issue on the repository if there's anything wrong with the website!",
    "There are more content than you might think. And it keeps growing!",
    "Mumble mumble...",
    "Egg: Not too important, not too unimportant.",
    'If you see null in tips, it\'s not a mistake. There actually exists a tip that says, well, "null"!',
    "PANDORA PARADOXXX",
    "I'm horribly near-sighted. I might become blind someday. That's scary...",
    "LGBTQ+ rights matters.",
    "Cheeses are good. I love eating 'em.",
    "undefined (this is fake, as well.)",
    "*brushing hair*",
    "676767676767676767676767676767676767676767676767676767676767676767676767",
    "I block whoever makes me mad.",
    "So tired.",
    "Ah, Saturday Tasogare. How cute she is!",
    "Where's Tsuki Tasogare?",
    "Don't you know what I don't know?",
    "Open source is good. Close source is bad.",
    "I fuckin' hate Windows.",
    "Why are you looking at a loser's webpage?",
    "Rendering texts correctly is way harder than you might think.",
    "This is my homepage.",
    "The life is in a mess.",
    "Mumbling on the keyboard, mumbling on the keyboard.",
    "祈 -我ら神祖と共に歩む者なり-",
    "There are some hidden content on the page.",
    "I'm kinda wanna sleep at this point.",
    "I'm done with it...",
    "Wanna get some friends... but hold on.",
    "Deno is a great runtime. And a great LSP.",
    "I like seeing Saturday Tasogare and Allison Allister together. They're just so sweet oh my god",
    "Why Japanese doesn't allow us to play ONGEKI?",
    "Pink is my favorite color.",
    "Akiyama Yuuki is Akiyama Mizuki's sister.",
    ":3",
    "Oh la la.",
    "QZKago Requiem",
    "I wish I could be Mizuki or Saturday...",
    "FONT TEST AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz0123456789~!@#$%^&*()`<>,./[]{}|\\'\"-_+=",
    "The font used on this website is called Liberation Serif.",
    "There is also a tip that is empty by the way.",
    "Ooh...",
    "Have I done this for 8266 times?",
    "Rhythm Doctor is a good game to play.",
    "I'm using paru as the AUR helper.",
    "I'm really tired writing these tips...",
    "Smoking...",
    "Recollect Lines",
    "Here is a secret way to reload the page. Do you know that?",
    "Most of GUI ignores keyboard centric user experience. Hence they sucks.",
    "Will anyone really read and explore my homepage? I don't know. I just randomly put anything I want to put here.",
    "I like tweaking my neovim config...",
    "Traditional medicine is a lie. There are only medicine (the modern one), and liars.",
    "I use neovim for almost everything.",
    "I can't see hope in my life.",
    "Do you know what I know?",
    "Don't forget to update your system.",
    "tmux is great, try learning how to use it.",
    "Vibe coding is a lie.",
    "I wish I could see Saturday on the page...",
    "Do you know how I shuffle the tips? I just Vi[!shuf<CR> and it's done. And also I need to put a ] here to prevent messing up indents in my editor.",
    "CHUNITHM is also a fun game to play.",
    "One of my best friends died in Mar 5, 2021 due to committing suicide.",
    "Hamasushi is delicious.",
    "Let's use Firefox, shall we?",
    "I hate writing shell scripts. So I just go straight writing a new project in Rust.",
    "There's a man in between, in between.",
    "Wanna have a Margherita Pizza? I love eating 'em.",
    'Akiyama Mizuki is a character from "Hatsune Miku: Colorful Stage". ',
    "null",
    "To be or not to be, that is the question.",
    "My telegram username is onion27 and here's the tip.",
    "ONGEKI is really really fun.",
    "Please respect to everyone's gender identity, and use the correct pronoun they claim. Use the gender neutral expression if you are not sure.",
    "Never forget to add semicolon after CSS statement...",
    "DELTARUNE is really fun to play.",
    "Windows is a horrible graphical centric operating system and it made lots of idiots who doesn't understand computers at all, and who is shouting idiot questions in the community and spreading it fucking everywhere",
    "Tips are just me mumbling alone in the late night. Don't care about it!",
    "I don't like drinking coke.",
    "There are a lot of hidden information on the page.",
    "The tips will be shuffled after writing, but some of them are written in order.",
    "I'm hungry...",
    "I'll take a break after writing this tip.",
    "vivid/stasis is a fun rhythm game, and it's free on Steam!",
    "Please refer to transgender people with correct pronouns.",
    "Racism, transphobic, homophobic and people like that will get an instant block from me.",
    "27 was my student number in the primary school, and Onion is my nickname given by a friend.",
    "The world is dumbass.",
    "I want to commit suicide time to time. The reason why I'm still alive is because they (ways to commit suicide) all looks painful (and they actually are).",
    "I want to start an ARG or something... but I don't really have a plan.",
    "maimai DX is not a washing machine!",
    "Why can't I sleep?",
    "acta est fabula, plaudite",
    "Even though I want to die everyday, I still sincerely wish everybody else to live healthily and happily. So, cheer up if you're reading this!",
    "Fuckoff X11!",
    "I can't think...",
    "STARCRASHERS",
    "Hyprland",
    "STARGAZERS",
    "Rolling on the ground, jumping over woods...",
    "Will there be another world after dying? I don't know. I tried, but I failed.",
    "I'm so tired...",
    "I fail on everything. I'm just a loser, I have to admit.",
    "Good night.",
    "I'm running out of money...",
    "Saturday Tasogare and Allison Tasogare(Allister) got married in the game polymorphite oh my god aaahhhhh i fuckin' love it",
    "maimai DX is fun to play.",
    "",
    "I'll never forget to add a comma after writing a tip... I just ran into problem because of that.",
    "Could you find Tsuki Tasogare?",
    "Barium chloride is bitter. Like, very very bitter. Never try eating this!",
    "Can I live in a story, instead of a boring and cruel world?",
    "There are many easter eggs in the page, just trigger them by typing random words on keyboard.",
    "I hate the real world, very, very much.",
    "Type her name.",
    "Writing Haskell is like training my brain.",
    "91",
    "Beware the man who speaks in hands.",
    "There are lots of garbage repository in my Github account. They were created by me when I was really, really young. Like I was literally a child that time.",
    "... wouldn't it be better for me to disappear from the world?",
    "AI sucks.",
    "Why am I writing these tips?",
    "Welcome to yet another recreational programming session, with 27Onion!",
    "Apple juice is good to drink.",
    '"25-ji, Nightcord de" means meeting on Nightcord in 25:00.',
    'Why do we say "good night"? \nBecause we want to wish each other happiness in our dreams. \nBecause we want to share the following day with each other. \nBecause we want our rests to matter just as much to us as our battles. \nWe say "good night" to bookend chapters of our lives, every single day. \nEvery single night. \nBut every "good night" is only a promise of a new day tomorrow. \nEven with each "goodbye", we wish to each other to see ourselves again. \nSo when we say "good night", it\'s not the end. \nIt\'s the promise at every dusk to soon see tomorrow\'s dawn. \n\nSee you tomorrow. \nGood night.',
    "Forsaken Tale",
    "Rust is a great programming language. Not perfect, but great enough.",
    "Do you know the famous KONAMI cheat code?",
    "Yah- hoo-!",
    "Do you know my telegram? You might find it in a tip.",
    "Trans women are WOMEN. \nTrans men are MEN.",
    "I love watching Tsoding streams.",
    "Modal keybinds are good!",
    "A brown fox jumps over the lazy dog.",
];

let current_tip = null;

/**
 * @returns {String}
 */
export function get_tip() {
    if (current_tip === null) {
        current_tip = TIPS[randomInt(0, TIPS.length)];
    }
    return current_tip;
}
