import { randomInt } from "./util.js";

export const TIPS = [
    "*brushing hair*",
    "Rolling on the ground, jumping over woods...",
    "There are a lot of hidden information on the page.",
    "Saturday Tasogare and Allison Tasogare(Allister) got married in the game polymorphite oh my god aaahhhhh i fuckin' love it",
    "I'm already using Deno everywhere. Who cares about NodeJS?",
    "maimai DX is not a washing machine!",
    "There's a man in between, in between.",
    "Vibe coding is a lie.",
    "Rendering texts correctly is way harder than you might think.",
    'If you see null in tips, it\'s not a mistake. There actually exists a tip that says, well, "null"!',
    "Why am I writing these tips?",
    "I block whoever makes me mad.",
    "祈 -我ら神祖と共に歩む者なり-",
    "91",
    ":3",
    "There are random music names in the tips. Hope you will see them, ha!",
    "Good night.",
    "FONT TEST AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz0123456789~!@#$%^&*()`<>,./[]{}|\\'\"-_+=",
    "To be or not to be, that is the question.",
    "I can't think...",
    "maimai DX is fun to play.",
    "You can create an issue on the repository if there's anything wrong with the website!",
    "I'm horribly near-sighted. I might become blind someday. That's scary...",
    "PANDORA PARADOXXX",
    "I'm running out of money...",
    "Oh la la.",
    '"25-ji, Nightcord de" means meeting on Nightcord in 25:00.',
    "Wanna get some friends... but hold on.",
    "I hate the real world, very, very much.",
    "Yah- hoo-!",
    "Deno is a great runtime. And a great LSP.",
    "Will anyone really read and explore my homepage? I don't know. I just randomly put anything I want to put here.",
    "Could you find Tsuki Tasogare?",
    "vivid/stasis is a fun rhythm game, and it's free on Steam!",
    "Hyprland",
    "Why Japanese doesn't allow us to play ONGEKI?",
    "The world is dumbass.",
    "Fuckoff X11!",
    "Egg: Not too important, not too unimportant.",
    "The tips will be shuffled after writing, but some of them are written in order.",
    "Recollect Lines",
    "I'm using paru as the AUR helper.",
    "Don't forget to update your system.",
    "27 was my student number in the primary school, and Onion is my nickname given by a friend.",
    "Do you know how I shuffle the tips? I just Vi[!shuf<CR> and it's done. And also I need to put a ] here to prevent messing up indents in my editor.",
    "Rhythm Doctor is a good game to play.",
    "Here is a secret way to reload the page. Do you know that?",
    "Do you know my telegram? You might find it in a tip.",
    "Rust is a great programming language. Not perfect, but great enough.",
    "CHUNITHM is also a fun game to play.",
    "I use neovim for almost everything.",
    "Where's Tsuki Tasogare?",
    "Akiyama Yuuki is Akiyama Mizuki's sister.",
    "The life is in a mess.",
    "Pink is my favorite color.",
    "It's not bad toe write C code sometimes.",
    "The font used on this website is called Liberation Serif.",
    "... wouldn't it be better for me to disappear from the world?",
    "My telegram username is onion27 and here's the tip.",
    "I want to start an ARG or something... but I don't really have a plan.",
    "There are many easter eggs in the page, just trigger them by typing random words on keyboard.",
    "I love watching Tsoding streams.",
    "Open source is good. Close source is bad.",
    "I like tweaking my neovim config...",
    "There is also a tip that is empty by the way.",
    "A brown fox jumps over the lazy dog.",
    "Let's use Firefox, shall we?",
    "There are more content than you might think. And it keeps growing!",
    "I'm kinda wanna sleep at this point.",
    "CLAUDIA -libertia-",
    "Ah...",
    "I can't see hope in my life.",
    "My MBTI is available somewhere...",
    "I wish I could see Saturday on the page...",
    "I hate writing shell scripts. So I just go straight writing a new project in Rust.",
    'Why do we say "good night"? Because we want to wish each other happiness in our dreams. Because we want to share the following day with each other. Because we want our rests to matter just as much to us as our battles. We say "good night" to bookend chapters of our lives, every single day. Every single night. But every "good night" is only a promise of a new day tomorrow. Even with each "goodbye", we wish to each other to see ourselves again. So when we say "good night", it\'s not the end. It\'s the promise at every dusk to soon see tomorrow\'s dawn. See you tomorrow. Good night.',
    "Type her name.",
    "Mumble mumble...",
    "",
    "AI sucks.",
    "Tips are just me mumbling alone in the late night. Don't care about it!",
    "Smoking...",
    "Hamasushi is delicious.",
    "So tired.",
    "I fuckin' hate Windows.",
    "Please respect to everyone's gender identity, and use the correct pronoun they claim. Use the gender neutral expression if you are not sure.",
    "acta est fabula, plaudite",
    "You can scroll on the webpage. You might already knew that.",
    "Apple juice is good to drink.",
    "I don't like drinking coke.",
    "Barium chloride is bitter. Like, very very bitter. Never try eating this!",
    "tmux is great, try learning how to use it.",
    "Beware the man who speaks in hands.",
    "I want to commit suicide time to time. The reason why I'm still alive is because they (ways to commit suicide) all looks painful (and they actually are).",
    "Even though I want to die everyday, I still sincerely wish everybody else to live healthily and happily. So, cheer up if you're reading this!",
    "I'm so tired...",
    "Will there be another world after dying? I don't know. I tried, but I failed.",
    'Akiyama Mizuki is a character from "Hatsune Miku: Colorful Stage". ',
    "Wanna have a Margherita Pizza? I love eating 'em.",
    "Most of GUI ignores keyboard centric user experience. Hence they sucks.",
    "Do you know the famous KONAMI cheat code?",
    "Transgender rights matters.",
    "Never forget to add semicolon after CSS statement...",
    "I'll never forget to add a comma after writing a tip... I just ran into problem because of that.",
    "Can I live in a story, instead of a boring and cruel world?",
    "Racism, transphobic, homophobic and people like that will get an instant block from me.",
    "There are some hidden content on the page.",
    "I'll take a break after writing this tip.",
    "Welcome to yet another recreational programming session, with 27Onion!",
    "I'm done with it...",
    "Do you know what I know?",
    "null",
    "DELTARUNE is really fun to play.",
    "QZKago Requiem",
    "Why are you looking at a loser's webpage?",
    "undefined (this is fake, as well.)",
    "This is my homepage.",
    "Forsaken Tale",
    "Don't you know what I don't know?",
    "Modal keybinds are good!",
    "Ooh...",
    "I fail on everything. I'm just a loser, I have to admit.",
    "There are lots of garbage repository in my Github account. They were created by me when I was really, really young. Like I was literally a child that time.",
    "Ah, Saturday Tasogare. How cute she is!",
    "ONGEKI is really really fun.",
    "Never touch the truth.",
    "STARCRASHERS",
    "676767676767676767676767676767676767676767676767676767676767676767676767",
    "I like seeing Saturday Tasogare and Allison Allister together. They're just so sweet oh my god",
    "LGBTQ+ rights matters.",
    "My birthday? ...it's on Feb 1st.",
    "I wish I could be Mizuki or Saturday...",
    "Cheeses are good. I love eating 'em.",
    "Why can't I sleep?",
    "Writing Haskell is like training my brain.",
    "What about playing UNDERTALE?",
    "I'm hungry...",
    "Please refer to transgender people with correct pronouns.",
    "Yoisaki Kanade, Asahina Mafuyu, Shinonome Ena and Akiyama Mizuki are members of 25-ji, Nightcord de.",
    "Have I done this for 8266 times?",
    "Mumbling on the keyboard, mumbling on the keyboard.",
    "STARGAZERS",
    "One of my best friends died in Mar 5, 2021 due to committing suicide.",
    "I'm really tired writing these tips...",
];

let current_tip = null;

/**
 * @returns {String}
 */
export function get_tip() {
    if (current_tip === null) {
        current_tip = TIPS[randomInt(0, TIPS.length)];
    }
    return current_tip;
}
