export const dialogsI18N = {
    "en_US": [
        ["* Welcome to \\[27Onion's Website\\]! ", "* Choose an \\[option\\]. "], // 0
        [ // 1
            "* Oh? About me?",
            "* My name is \\[27Onion\\].",
            "* My Github account is called onion108.\\n* You can search it."
        ],
        [ // 2
            "* I'm learning \\[Rust\\] these days.\\n* It's our responsibility to rewrite \\[everything\\] in \\[Rust\\]!!! Ooh-hoo.",
            "* I can also write Golang, C, C++, Java, Kotlin, C# and more.",
            "* You see, the website is written in \\[Typescript\\].",
        ],
        [ // 3
            "* H3Y!!!! EVERY!!!!",
            "* I'm [[27Onion G. 27Onion]]!!!!!",
            "* Oh you the [[$4.99 Little Sponge]]!",
            "* You need some\\n* something",
            "* Make you [[BIG]]!! Make me [[BIG]]!!!",
            "* [[Hyperlink Blocked]].",
        ],
        [ // 4
            "* Oh! I've got a lot of \\[friends\\].",
            "* Yeah, you can be one, too!!!! I mean.",
        ],
        [ // 5
            "* ...",
            "* I \\[had\\] one...",
            "* But... but she...",
            "* ...",
            "* Ft=mv...",
            "* (Please... don't... I'm so afraid... )",
            "* \\{&@#%%$^%$@&^%$_msg_6_$&^%*!@&^%$*#\\}",
            "* ...",
            "* I'm sorry.",
            "* Forget it.",
            "* \\W. \\W. \\W. ",
            "* Don't worry about me! ",
            "* I still have \\[Yuhang Hu\\]. I haven't lost everything. \\n* Be positive, my friend! ",
        ],
        [ // 6
            "* [DELETED]",
        ],
        [ // 7
            "* Yes, I'm fine! Thanks. ",
        ],
        [ // 8
            "* ???",
            "* ?????",
            "* ??????????????????????????",
            "* What",
            "* the",
            "* fuck",
        ],
        [ // 9
            "* \\[Dec 27, 2007\\]. And \\{Mar 5, 2021\\}.",
            "* \\[Jan 13\\] as well. ",
        ],
        [ // 10
            "* \\[Undertale\\], \\[Deltarune\\] o'course. ",
            "* Oh, and \\[Minecraft\\]. ",
            "* \\[Super Mario Bros\\] looks great, but I can never play to the end.",
        ],
        [ // 11
            "* So you're asking my \\[soul\\]? ",
            "* Nothing special. I'm just a monster looks like a human. ",
            "* My soul is half white & half black. ",
            "* As for details: The left half of my soul is black and the right half is white. ",
            "* Attention. My soul is an upside-down heart, since I'm not a human at all. ",
            "* I have \\{Determination\\}. ",
        ],
        [ // 12
            "* ...?",
            "* Ehh... Nothing. ",
            "* You can a-ask me everythin' in the o-options down he-here! ",
            "* I have no-nothing to hi-hide. "
        ],
        [ // 13
            "* We are trying to add this feature. ",
            "* But first I need to read this code from months ago. ",
            "* It seems that I cannot understand it anymore. ",
        ],
        [ // 14
            "* Really? \\n* Thank you! ",
            "* If you really like it, I may want to make a \\[framework\\] of it and publish it. ",
            "* The source code of this website is \\[in a mess\\] 'cause I'm not taking it seriously. ",
            "* wwwwwwww",
        ],
        [ // 15
            "* We-well, that's ok.",
            "* Everybody have their own favorites, I mean. ",
        ],
        [ // 16
            "* Yes, I can speak Chinese. ",
            "* 我只是懒得做中文的本地化而已。\\n* (For English speakers: I'm just too lazy to do the localization for Chinese. )",
            "* 如果你开发过程序，你应该知道\\[本地化\\]是一件很麻烦的事情。\\n* (For English speakers: You should know that it's very hard to do \\[localizations\\] if you've developed applications. )",
        ],
        [ // 17
            "* I felt lost...",
            "* ...",
            "* DARKNESS...",
            "* SADNESS...",
            "* \\{DEATH\\}.",
            "* \\{KILL\\} ME. PLEASE...",
        ],
        [ // 18
            "* No. I'm not using any frameworks. ",
            "* It's in 100% \\[Vanilla Typescript\\]. ",
            "* I love the \\[static type system\\]. ",
            "* If you mean the \\[typewriter system\\], I just want to say, it's all by myself. ",
        ],
        [ // 19
            "* I've just done some \\[parse\\] works. ",
            "* As you see, the \\[highlighted codes\\] are in the format like this: \\n* \"\\\\\\\\[Hightlighted Text\\\\\\\\]\"",
            "* And I just did a little parse. ",
        ],
        [ // 20
            "* (Queen-styled Laugh)",
            "* Oh",
            "* LMAO",
            "* I Am Known As Serial Number \\[2A7MOLNKIAOVNE\\]",
            "* Or For Short 27Onion",
            "* Are You Satisfied With It",
            "* LMAO",
            "* Well You Seems Really Like It",
            "* Don't You",
            "* Well Have Fun",
            "* I'm Gotta Go LMAO",
        ],
        [ // 21
            "\\s* hey kid.",
            "\\s* listen. ",
            "\\s* have you ever seen a \\[flowey that can speak\\]?",
            "\\s* yes. that is it.",
            "\\s* the \\[echo flower\\].",
            "\\s* well i'm goin' to sleep.",
            "\\s* good luck, kid. ",
        ],
        [ // 22
            "\\pHEY HUMAN!!! IT'S ME!! THE GREAT 27ONION!!",
            "\\pI'VE BROUGHT MY BEST SPAGHETTI FOR YOU!!",
            "\\pTHE SPAGHETTI IS VERY GREAT! IT CAN MAKE YOU-",
            "* ...[[Big]]! Make me [[Big]]!",
            "* And [[Desert you]]!!!",
            "\\pWHAT'S THAT? WELL, ANYWAY!!I'LL NEVER-",
            "* [[Gonna Give You Up]]~ ",
            "\\pHEY YOU! WHAT ARE YOU DOING HERE!!",
            "* Woah!! AR3N'T you the ",
            "* Light-n3R!! Hey hey hey!!!",
            "\\pNYEH? LIGHTN3R? WHO IS LIGHTN3R?",
            "* You the [[$4.99 Little Sponges]]!!",
            "* You must N33D some [[Hyperlink Blocked]].",
            "* Hahahaha! [[Hyperlink Blocked]]!!",
            "\\pTHE GUY MUST BE CRAZY.",
            "* (You nodded your head to show you're agree with her.)",
            "* Oh",
            "* LMAO",
            "* I Just Met A Flower",
            "* It Said",
            "* Error",
            "* LMAO",
            "* It's Just Very Funny LMAO",
            "\\pWOWIE! SO MANY PEOPLE HERE!",
            "\\pWELL, HUMAN-",
            "\\pI'M GOTTA GO NOW!!! CALL ME IF YOU WANT!!",
            "* Good Bye My Sweetie LOL",
            "* (Click...) ",
        ],
        [ // 23
            "* My gender? ",
            "* I am a \\[girl\\], o'course. ",
            "* Any problems here? ",
            "* Oh... Ok. I know what you want to say. ",
            "* Yes I'm \\[MtF\\]. ",
            "* But it doesn't influence anything! ",
        ],
        [ // 24
            "* Yes... ",
            "* That's \\[Wolfys Nebell\\]...",
            "* ... ",
        ],
        [ // 25
            "* \\[Today\\]. And \\{Mar 5, 2021\\}.",
        ],
        [ // 26
            "* I'm sorry... ",
            "* But you're not \\[Wolfys Nebell\\]. ",
        ],
        [ // 27
            "* What? You really want it? ",
            "* Ok, I can add this feature in seconds... I guess... ",
            "* Please wait for a while.\\W.\\W. \\W",
            "* It's done now! ",
            "* Test it. ",
        ],
        [ // 28
            "* If you mean the alive one, it's currently, without doubt, \\[Yuhang Hu\\].",
            "* \\[Wolfys Nebell\\] IS important, but...",
            "* Life is still going on, y'know. \\n* Life is still \\[GOING ON\\]...",
            "* Well, \\[Yuhang Hu\\] is now my most-trusted friend.\\n* ...in those who are still alive. ",
        ],
    ],
};

export const otherI18N = {
    "en_US": {
        "onion27.question.0": "About you?",
        "onion27.question.1": "What languages you are using?",
        "onion27.question.2": "Spamton-like speak?",
        "onion27.question.3": "Your friend? 114514",
        "onion27.question.4": "You TRUE friend?",
        "onion27.question.5": "How are you?",
        "onion27.question.6": "*Hug*",
        "onion27.question.7": "The most special day for you? ",
        "onion27.question.8": "Video games you like?",
        "onion27.question.9": "Your Undertale soul?",
        "onion27.question.10": "Are you hiding something?",
        "onion27.question.11": "I love the style of this webpage.",
        "onion27.question.12": "The webpage is just a junk.",
        "onion27.question.13": "Is there a Chinese version?",
        "onion27.question.14": "[Hidden Message No.17]",
        "onion27.question.15": "Did you use any framework to build this website?",
        "onion27.question.16": "How do you color the text?",
        "onion27.question.17": "Queen-like speak?",
        "onion27.question.18": "Sans-like speak?",
        "onion27.question.19": "Papyrus-like speak?",
        "onion27.question.20": "You gender?",
        "onion27.question.21": "Your best friend now?",

        "onion27.operation.next": "Next",
        "onion27.operation.skip": "Skip",
        "onion27.sections.options": "Options",
        "onion27.sections.navigation": "Navigation",

        "onion27.special.rip_wolfys": "* Repose en paix, \\[Wolfys Nebell (2007-2021)\\].",

        "onion27.dialog.thats_all": "* That's all.\\n* Choose another \\[option\\] to see.",
        "onion27.dialog.boring50": "* Well, don't you have something more important to do?",
        "onion27.dialog.boring100": "* ...",
        "onion27.dialog.secret0": "* Huh, you are really boring, huh? ",
        "onion27.dialog.secret1": "* Well, you may want to take a look in the code. ",
        "onion27.dialog.secret2": "* \\{YOU WILL FIND SOMETHING, FULL OF DARKNESS\\}.",
    }
}
